controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


arm_controller:
  ros__parameters:
      state_publish_rate: 100.0     
      joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - end_effector_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      action_monitor_rate: 20.0
      allow_partial_joints_goal: true

gripper_controller:
  ros__parameters: 
      state_publish_rate: 100.0
      joints:
        - right_gripper_arm_joint
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity
      action_monitor_rate: 20.0
      allow_partial_joints_goal: true
