# Default initial positions for aarm's ros2_control fake system

initial_positions:
  end_effector_joint: 0
  joint_1: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0
  joint_5: 0
  right_gripper_arm_joint: 0